parameters:
    netgen_html_pdf_api.class: Netgen\HtmlPdfApiBundle\Component\HtmlPdfApi
    netgen_html_pdf_api.http_client.guzzle.class: Netgen\HtmlPdfApiBundle\Component\HttpClient\Guzzle
    netgen_html_pdf_api.http_client.curl.class: Netgen\HtmlPdfApiBundle\Component\HttpClient\Curl
    netgen_html_pdf_api.validator.htmlpdfapivalidator.class: Netgen\HtmlPdfApiBundle\Component\Validator\HtmlPdfApiValidator

services:
    netgen_html_pdf_api:
        class: %netgen_html_pdf_api.class%
        arguments:
            - @netgen_html_pdf_api.http_client
            - @netgen_html_pdf_api.validator

    netgen_html_pdf_api.http_client:
        alias: netgen_html_pdf_api.http_client.guzzle

    netgen_html_pdf_api.validator:
        alias: netgen_html_pdf_api.validator.htmlpdfapivalidator

    netgen_html_pdf_api.http_client.guzzle:
        class: %netgen_html_pdf_api.http_client.guzzle.class%
        arguments:
            - %netgen_html_pdf_api.host%
            - %netgen_html_pdf_api.token%
            - %netgen_html_pdf_api.http_client.guzzle.service_json_location%
            - %kernel.root_dir%

    netgen_html_pdf_api.http_client.curl:
        class: %netgen_html_pdf_api.http_client.curl.class%
        arguments:
            - %netgen_html_pdf_api.host%
            - %netgen_html_pdf_api.token%

    netgen_html_pdf_api.validator.htmlpdfapivalidator:
        class: %netgen_html_pdf_api.validator.htmlpdfapivalidator.class%