parameters:
#    netgen_html_pdf_api.example.class: Netgen\HtmlPdfApiBundle\Example

services:
#    netgen_html_pdf_api.example:
#        class: %netgen_html_pdf_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    netgen_html_pdf_api:
        class: Netgen\HtmlPdfApiBundle\Component\HtmlPdfApi
        arguments:
            - %netgen_html_pdf_api.host%
            - %netgen_html_pdf_api.token%
